# layout: sidebar
layout: stacked
# style: light
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

# permalink: /:year/:month/:day/:title/

collections:
  apps:
    output: true
    permalink: /app/:name
  appsectiontestapps:
    output: true
    permalink: /app/test-app/:name/

defaults:
  - scope:
      path: ''
      type: 'apps'
    values:
      layout: 'app'
  - scope:
      path: '' # an empty string here means all files in the project
      type: 'posts'
    values:
      layout: 'post'
  - scope:
      path: ''
    values:
      layout: 'default'
